// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdAxpxwZmZRAIy94sEbMaf3pqV-euPL1c',
    appId: '1:760099392262:web:5a91ab21ce7a2786002c87',
    messagingSenderId: '760099392262',
    projectId: 'restaurant-management-sy-db090',
    authDomain: 'restaurant-management-sy-db090.firebaseapp.com',
    storageBucket: 'restaurant-management-sy-db090.firebasestorage.app',
    measurementId: 'G-9R35JT1DX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIKjG1NiV7Xm2DKR6LOdgwgTthsL8_qrQ',
    appId: '1:760099392262:android:dfa4f4239ec7f7b1002c87',
    messagingSenderId: '760099392262',
    projectId: 'restaurant-management-sy-db090',
    storageBucket: 'restaurant-management-sy-db090.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwwCMV9pPNC_TVgm7GMJHsESdv44JeW_E',
    appId: '1:760099392262:ios:58b570e90841c827002c87',
    messagingSenderId: '760099392262',
    projectId: 'restaurant-management-sy-db090',
    storageBucket: 'restaurant-management-sy-db090.firebasestorage.app',
    iosBundleId: 'com.example.restaurantManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwwCMV9pPNC_TVgm7GMJHsESdv44JeW_E',
    appId: '1:760099392262:ios:58b570e90841c827002c87',
    messagingSenderId: '760099392262',
    projectId: 'restaurant-management-sy-db090',
    storageBucket: 'restaurant-management-sy-db090.firebasestorage.app',
    iosBundleId: 'com.example.restaurantManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdAxpxwZmZRAIy94sEbMaf3pqV-euPL1c',
    appId: '1:760099392262:web:78030413212516fe002c87',
    messagingSenderId: '760099392262',
    projectId: 'restaurant-management-sy-db090',
    authDomain: 'restaurant-management-sy-db090.firebaseapp.com',
    storageBucket: 'restaurant-management-sy-db090.firebasestorage.app',
    measurementId: 'G-HPC4BNDND8',
  );
}
